# Generated by Django 4.2 on 2025-05-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='库位编码')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='库位名称')),
                ('row', models.CharField(blank=True, max_length=10, null=True, verbose_name='行号')),
                ('column', models.CharField(blank=True, max_length=10, null=True, verbose_name='列号')),
                ('level', models.CharField(blank=True, max_length=10, null=True, verbose_name='层号')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='长度(m)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='宽度(m)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='高度(m)')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大承重(kg)')),
                ('status', models.CharField(choices=[('empty', '空闲'), ('occupied', '占用'), ('reserved', '预留'), ('locked', '锁定'), ('damaged', '损坏')], default='empty', max_length=20, verbose_name='状态')),
                ('is_pickable', models.BooleanField(default=True, verbose_name='是否可拣货')),
                ('is_storable', models.BooleanField(default=True, verbose_name='是否可存储')),
                ('temperature_controlled', models.BooleanField(default=False, verbose_name='是否温控')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库位',
                'verbose_name_plural': '库位',
                'db_table': 'warehouse_location',
                'ordering': ['zone', 'row', 'column', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='仓库描述')),
                ('address', models.TextField(blank=True, null=True, verbose_name='仓库地址')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总面积(㎡)')),
                ('usable_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='可用面积(㎡)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='仓库高度(m)')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='仓库管理员')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouse_warehouse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='库区编码')),
                ('name', models.CharField(max_length=50, verbose_name='库区名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='库区描述')),
                ('zone_type', models.CharField(choices=[('storage', '存储区'), ('picking', '拣货区'), ('shipping', '发货区'), ('receiving', '收货区'), ('return', '退货区'), ('quarantine', '隔离区')], max_length=20, verbose_name='库区类型')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='长度(m)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='宽度(m)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='高度(m)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '库区',
                'verbose_name_plural': '库区',
                'db_table': 'warehouse_zone',
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库'), ('move', '移库'), ('adjust', '调整'), ('freeze', '冻结'), ('unfreeze', '解冻'), ('count', '盘点')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联单号')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location', verbose_name='库位')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库操作日志',
                'verbose_name_plural': '仓库操作日志',
                'db_table': 'warehouse_operation_log',
                'ordering': ['-operation_time'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.zone', verbose_name='所属库区'),
        ),
        migrations.CreateModel(
            name='WarehouseEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, verbose_name='设备编码')),
                ('equipment_type', models.CharField(choices=[('forklift', '叉车'), ('conveyor', '传送带'), ('scanner', '扫码器'), ('printer', '打印机'), ('scale', '电子秤'), ('camera', '监控摄像头'), ('sensor', '传感器'), ('other', '其他')], max_length=20, verbose_name='设备类型')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号')),
                ('status', models.CharField(choices=[('normal', '正常'), ('maintenance', '维护中'), ('fault', '故障'), ('retired', '报废')], default='normal', max_length=20, verbose_name='状态')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='保修期至')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '仓库设备',
                'verbose_name_plural': '仓库设备',
                'db_table': 'warehouse_equipment',
                'ordering': ['-created_at'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('zone', 'code')},
        ),
    ]
