# Generated by Django 4.2 on 2025-05-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='品牌名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='品牌编码')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='品牌Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='品牌描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'products_brand',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'products_category',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='供应商编码')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='简称')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='税号')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行账户')),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True, verbose_name='付款条件')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用'), ('blacklist', '黑名单')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'products_supplier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品编码')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='简称')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='型号')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='长度(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='宽度(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='高度(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='重量(kg)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='体积(cm³)')),
                ('package_unit', models.CharField(default='件', max_length=20, verbose_name='包装单位')),
                ('package_quantity', models.IntegerField(default=1, verbose_name='包装数量')),
                ('storage_type', models.CharField(choices=[('normal', '常温'), ('cold', '冷藏'), ('frozen', '冷冻'), ('dry', '干燥'), ('humid', '保湿')], default='normal', max_length=20, verbose_name='存储类型')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最低温度(℃)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最高温度(℃)')),
                ('humidity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最低湿度(%)')),
                ('humidity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最高湿度(%)')),
                ('safety_stock', models.IntegerField(default=0, verbose_name='安全库存')),
                ('min_stock', models.IntegerField(default=0, verbose_name='最低库存')),
                ('max_stock', models.IntegerField(default=0, verbose_name='最高库存')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本价')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='销售价')),
                ('shelf_life_days', models.IntegerField(blank=True, null=True, verbose_name='保质期(天)')),
                ('is_batch_managed', models.BooleanField(default=False, verbose_name='是否批次管理')),
                ('is_serial_managed', models.BooleanField(default=False, verbose_name='是否序列号管理')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用'), ('discontinued', '停产')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='商品分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.supplier', verbose_name='默认供应商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='条形码')),
                ('barcode_type', models.CharField(choices=[('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upc', 'UPC'), ('code128', 'Code 128'), ('code39', 'Code 39'), ('qr', 'QR码'), ('custom', '自定义')], default='ean13', max_length=20, verbose_name='条形码类型')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主条码')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品条码',
                'verbose_name_plural': '商品条码',
                'db_table': 'products_barcode',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='供应商商品编码')),
                ('supplier_product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='供应商商品名称')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='采购价')),
                ('min_order_quantity', models.IntegerField(default=1, verbose_name='最小订购量')),
                ('delivery_days', models.IntegerField(blank=True, null=True, verbose_name='交期(天)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='是否首选供应商')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '商品供应商',
                'verbose_name_plural': '商品供应商',
                'db_table': 'products_product_supplier',
                'ordering': ['-is_preferred', '-created_at'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
